# Generated by Django 4.1.7 on 2023-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
